10050 10052 
10012 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
10013 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
10016 sleep 3
10040 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
10041 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
10044 sleep 3
10050 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
10051 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
10052 sh -xe /home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh
10054 sleep 3

10081 10083
10012 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
10013 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
10016 sleep 3
10040 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
10041 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
10044 sleep 3
10050 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
10051 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
10054 sleep 3
10081 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt'; wait) >&- 2>&- &
10082 sh -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7' -a \! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/jenkins-result.txt'; wait) >&- 2>&- &
10083 sh -xe /home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-0aba97f7/script.sh
10085 sleep 3

sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
  └─sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-9ee07e89/jenkins-result.txt'; wait) >&- 2>&- &
      └─sleep,8295 3

sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
  └─sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/output.txt' 2> '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-log.txt'; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-cfc0d02f/jenkins-result.txt'; wait) >&- 2>&- &
      └─sleep,8295 3

sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
  ├─sh,8295 -c ({ while [ -d '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc' -a \\! -f '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt' ]; do touch '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt'; sleep 3; done } & jsc=durable-f72947d02359bb15a9d2d1d401c72819; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh' > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-log.txt' 2>&1; echo $? > '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp'; mv '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt.tmp' '/home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/jenkins-result.txt'; wait) >&- 2>&- &
  │   └─sleep,8295 3
  └─sh,8295 -xe /home/admin/.jenkins/workspace/jenkins-demo_develop@tmp/durable-74715dbc/script.sh
      └─pstree,8295 -ahgGls admin

      mvn help:evaluate -Dexpression=project.build.finalName | grep \"^[^\\[]\"
      mvn help:evaluate -Dexpression=project.packaging | grep \"^[^\\[]\"
      jps | grep `mvn help:evaluate -Dexpression=project.build.finalName | grep "^[^\\[]"`.`mvn help:evaluate -Dexpression=project.packaging | grep "^[^\\[]"` | awk '{print $1}'

      `mvn help:evaluate -Dexpression=project.build.finalName | grep "^[^\\[]"`.`mvn help:evaluate -Dexpression=project.packaging | grep "^[^\\[]"`

      jps | grep `mvn help:evaluate -Dexpression=project.build.finalName | grep "^[^\\[]"`.`mvn help:evaluate -Dexpression=project.packaging | grep "^[^\\[]"` | awk '{print $1}'
      jps | grep $(mvn help:evaluate -Dexpression=project.build.finalName | grep "^[^\\[]").$(mvn help:evaluate -Dexpression=project.packaging | grep "^[^\\[]") | awk '{print $1}'
      printf "%s\n" $(jps | grep $(mvn help:evaluate -Dexpression=project.build.finalName | grep "^[^\\[]").$(mvn help:evaluate -Dexpression=project.packaging | grep "^[^\\[]")) | egrep '^[0-9]+$'
